### ISSUE TITLE
Error in Side Effects documentation

### ISSUE THREAD

**Issue by mosofsky** [freeletics/CoRedux#122]
[The documentation for side effects](https://github.com/freeletics/CoRedux#side-effects) says "Let's add an side effect that makes a network request each time when action is CalculatorAction.Add and current state is **9**." But the implementation doesn't appear to look for for 9, it seems to look for any positive number:

```
if (inputAction is CalculatorAction.Add &&
                stateAccessor() >= 0) {
```

Maybe `stateAccessor() >= 0` should be changed to `9 == stateAccessor()`

Moreover, the example below seems wrong too:

```
storeWithSideEffect.subscribe { state -> updateUI(state) }
storeWithSideEffect.dispatch(CalculatorAction.Deduct(1))
// Current state will become -1
storeWithSideEffect.dispatch(CalculatorAction.Add(11))
// Current state will become 10 and network request will happen
```

Maybe the last two lines should be changed to:

```
storeWithSideEffect.dispatch(CalculatorAction.Add(10))
// Current state will become 9 and network request will happen
```

**Comment by Tapchicoma** [comment]
You are correct, description in readme has mistakes. I will update it.

Thank you for noticing it.
