### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by kawpii** [freeletics/CoRedux#129]
It is good to have coroutine based implementation of MVI. I wonder whether you guys consider this production ready?

Also wondering is there any difference between [Vector](https://github.com/haroldadmin/Vector) vs CoRedux?

**Comment by Tapchicoma** [comment]
Internally, we are still using RxJava 2 and RxRedux in our project. Both CoRedux and [FlowRedux](https://github.com/freeletics/flowredux) we created to explore possible implementations of the same approach as RxRedux using Kotlin coroutines. RxJava 3 was recently announced to hit stable release pretty soon, meaning we need to choose either we will go with RxJava2 -> RxJava3 migration route or will choose using coroutines implementation (could be via combining both CoRedux and FlowRedux approaches).

CoRedux itself should be stable and production ready. If you will hit any bug, please open an issue and we will fix it.

I haven't used Vector, but here is my thoughts after reading project readme:
- Vector is tied to Android, while CoRedux does not have any dependencies on Android SDK. Possibly in the future CoRedux could add additional libraries that simplifies using it from Android side.
- CoRedux does not enforce usage of `ModelState` interface for your state machine state classes
- In Vector you will use on state class, while CoRedux does not enforce it - you could use sealed class hierarchy
- Vector does not have side effects concepts and I am not sure if this library ensures predefined order of states.
This are really rough thoughts regarding the differences between this libraries.

**Comment by kawpii** [comment]
Thanks for the response!
