### ISSUE TITLE
Combine reducers

### ISSUE THREAD

**Issue by befrvnk** [freeletics/CoRedux#17]
A function to combine reducers could help splitting up the reducer into smaller parts.
With the current approach a single reducer is used to adapt the state for many screens. For complex screens this can become complicated to manage as the reducer function becomes bigger.
A solution to this problem could be a function to combine reducers. The same problem applies to side effects which are only used for specific screens.

```kotlin
fun combineReducers(reducers: Set<Reducer>): Reducer<States, Actions> =
  { state, action ->
    reducers.fold(state) { subState, subReducer -> subReducer.reduce(subState, action) }
  }
```

__Current approach__
```kotlin
sealed class Actions {
  object ScreenAAction : Actions()
  object ScreenBAction : Actions()
}

sealed class States {
  object ScreenAState : States()
  object ScreenBState : States()
}

reducer: Reducer<States, Actions> = {
  state, action ->
    when (action) {
      is Actions.ScreenAAction -> States.ScreenAState()
      is Actions.ScreenBAction -> States.ScreenBState()
      else -> state
}
```

__Suggested approach__
```kotlin
/*
 * Common model
 */
sealed class Actions
sealed class States

fun combineReducers(reducers: Set<Reducer>): Reducer<States, Actions> =
  { state, action ->
    reducers.fold(state) { subState, subReducer -> subReducer.reduce(subState, action) }
  }

val reducer = combineReducers(setOf(reducerA, reducerB))

/*
 * Model for screen A
 */
object ScreenAAction : Actions()

object ScreenAState : States()

val reducerA: Reducer<States, Actions> = {
  state, action ->
    when (action) {
      is ScreenAAction -> ScreenAState()
      else -> state


/*
 * Model for screen B
 */
object ScreenBAction: Actions()

object ScreenBState : States()

val reducerB: Reducer<States, Actions> = {
  state, action ->
    when (action) {
      is ScreenBAction -> ScreenBState()
      else -> state
```

**Comment by sockeqwe** [comment]
I think on a larger scale (like we are going to reach at Freeletics) where maybe multiple teams work on the same reduxstore and different actions, then it makes sense to talk about `SelfReducableAction` and move the reducer functionality into the `Action`.

Example:

```kotlin
sealed class SelfReducableAction<State> {

     abstract fun reduce(state : State) : State

     data class Action1 (val foo : Foo : SelfReducableAction<State> {
            override fun reduce(state : State) : State {
                 return state.copy(foo = this.foo)
           }
      }
}
```

**Comment by befrvnk** [comment]
@sockeqwe I like the idea! I am not sure if that works but is something like this possible too?

```kotlin
fun selfReducableAction(action: Action): (State) -> State = {
  state -> state.copy(foo = action.foo)
}
```

**Comment by sockeqwe** [comment]
I just realized that I forgot to include the `fun reducer()` in my snipped above:

```kotlin
fun reducer(action : SelfReducableAction<State>, state: State) = action.reduce(state)
```

```kotlin

coroutineScope
        .createStore(
            sideEffects = listOf( ... ),
            reducer = ::reducer
        )
```

or are we talking about two different things?

**Comment by Tapchicoma** [comment]
As I understand it correctly, @fraherm wants to combine multiple reducers, that uses the same `sealed class State` and `sealed class Action`, into one single reducer. Though for his proposal, I have enforce `reducers` type to clearly indicated that ordering matters(vararg becomes `Array`):
```kotlin
fun combineReducers(vararg reducers: Reducer): Reducer
```
Otherwise iterating over `reducers` in non-ordered way may lead to unpredictable state.

@sockeqwe proposal goes into other direction and I am not sure if should be a part of CoRedux - better to discuss it in a separate issue.
