### ISSUE TITLE
Add default `createStore` and `SideEffect` name parameter implementation.

### ISSUE THREAD

**Issue by Tapchicoma** [freeletics/CoRedux#35]
To simplify usage of `SideEffect` interface, it would be nice to add default implementation to `val name: String` parameter.

Possible inspiration can be taken from Timber library: https://github.com/JakeWharton/timber/blob/master/timber/src/main/java/timber/log/Timber.kt#L204, though this will be available only on jvm target.

**Comment by sockeqwe** [comment]
Timber 5.0 is just around the corner and will also add some initial support for multiplatform (not targeting any other platform but jvm at the moment.

We could maybe take some inspiration from there once the Timber 5.x also support other platforms ...

On a side note: What do you think about removing the `name` property from `SideEffect`? By doing so one could also just use any regular function matching the SideEffect signature  (similar to RxRedux) and reference it with `::`

**Comment by Tapchicoma** [comment]
> Timber 5.0 is just around the corner and will also add some initial support for multiplatform (not targeting any other platform but jvm at the moment.

As far as I know, multiplatform idea for Timber was dropped. If it will support, I am curious how tag extraction will look like.

> What do you think about removing the name property from SideEffect? By doing so one could also just use any regular function matching the SideEffect signature (similar to RxRedux) and reference it with ::

I still think that it is pretty important to have constant `name` for logging purposes (especially in visualizing tool for CoRedux). It doesn't add much burden on developer, but helps tooling. Having default `name` implementation should reduce Burden even more.

This issue is good further improvement of CoRedux, but, imho, is not crucial for first release.
