### ISSUE TITLE
Log events lost if the input channels subscribes after the broadcast

### ISSUE THREAD

**Issue by inorichi** [freeletics/CoRedux#63]
In the [Logger](https://github.com/freeletics/CoRedux/blob/v1.1.0/library/core/src/main/kotlin/com/freeletics/coredux/Logging.kt#L155-L166) constructor, when the broadcast channel subscribes after the inputs (race condition) the store start event is lost and the app crashes [here](https://github.com/freeletics/CoRedux/blob/v1.1.0/library/log/common/src/main/kotlin/com/freeletics/coredux/log/common/LoggerLogSink.kt#L25).

This is easily reproducible if you add a `delay(100)` just before `broadcastChannel.openSubscription().toChannel(it)`.

A possible fix is opening the broadcast channels subscriptions before launching the coroutines, like so:

```kt
logSinks.map { broadcastChannel.openSubscription() to it }.forEach { (recv, send) ->
  scope.launch(context = Dispatchers.Default) {
    recv.toChannel(send)
  }
}
scope.launch(context = Dispatchers.Default) {
  inputLogEventsChannel.toChannel(broadcastChannel)
}
```

**Comment by Tapchicoma** [comment]
I was able to reproduce the issue with adding proposed `delay(100)`. Now I need to figure out how to write proper test to this issue before fixing it :thinking:

**Comment by inorichi** [comment]
I don't think that's going to be easy, and I'm not sure it's really needed... I'd just ignore it.

Btw I don't know why I used map, it's better to keep the `forEach` and do `val broadcastChannelSubscription = broadcastChannel.openSubscription()` before `launch`


Edit: Also, this issue is explained in the docs of `ArrayBroadcastChannel`:
```
 * **Note**, that elements that are sent to this channel while there are no
 * [openSubscription] subscribers are immediately lost.
```

**Comment by inorichi** [comment]
Actually, do we really need the broadcast channel at all?

I think this is a better approach (unless I'm missing something), using a single coroutine:

```kt
  init {
    if (loggingEnabled) {
      scope.launch(context = Dispatchers.Default) {
        for (event in inputLogEventsChannel) {
          logSinks.forEach { it.send(event) }
        }
      }
    }
  }
```

**Comment by Tapchicoma** [comment]
Actually you are right - dropped `BroadcastChannel` from implementation :+1:
